### ISSUE TITLE
about MEANean and STDDEV of places2

### ISSUE THREAD

**Issue by NerminSalem** [bobqywei/inpainting-partial-conv#7]
i have another question regarding if i trained with another dataset should mean and stddev values in places2_train differ? and if these values will differ how to calculate them.
thanks alot

**Comment by bobqywei** [comment]
Yea usually those values are provided by the source, so if they differ much from the values I used (Places2/ImageNet) you should change them for better normalisation results.

**Comment by NerminSalem** [comment]
Thanks alot for your help, its really appriated 
One last question, i downloaded the mask datasets and resized them to 256*256 but couldn't reverse the black and white regions. Can u help?

**Comment by bobqywei** [comment]
No problem! And yeah, one word lol - PIL.ImageOps.invert

**Comment by NerminSalem** [comment]
I didn't think it is that easy🙈🙈🙈
Thanks alot u r the best
