### ISSUE TITLE
About the loss and input

### ISSUE THREAD

**Issue by FindTheAnswer** [bobqywei/inpainting-partial-conv#9]
Why the weights of the losses are not the same as the orginal paper?
Why the input is gt*mask?

**Comment by erhuodaosi** [comment]
> Why the weights of the losses are not the same as the orginal paper?
> Why the input is gt*mask?

gt*mask represents local response, you could get the answer in the paper,this is what partical convolution defined.As for the first question,I am confused,have you work it out,the weight of the loss is different with the original paper。

I have another question for training,have you met such similar question:
(py3) [fl@ibcu05 place2]$ python train.py
Loaded training dataset with 1434892 samples and 55116 masks
Loaded model to device...
Setup Adam optimizer...
Setup loss function...

EPOCH:0 of 3 - starting training loop from iteration:0 to iteration:89680

0%| | 0/89680 [00:00<?, ?it/s]
Traceback (most recent call last):
File "train.py", line 141, in 
loss_dict = loss_func(image, mask, output, gt)
File "/home/fl/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
File "/home/fl/place2/loss.py", line 94, in forward
loss_dict["tv"] = total_variation_loss(composed_output, self.l1) * LAMBDAS["tv"]
File "/home/fl/place2/loss.py", line 50, in total_variation_loss
loss = l1(image[:, :, :, :-1] - image[:, :, :, 1:]) + l1(image[:, :, :-1, :] - image[:, :, 1:, :])
File "/home/fl/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in call
result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'target'

I would very appreciate if you could help me, thank you!

**Comment by bobqywei** [comment]
@FindTheAnswer Yea I think I was experimenting at the time with higher style loss weighting, you can definitely tweak them accordingly though
